package com.cevelop.gslator.tests.suites;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

import com.cevelop.gslator.tests.tests.checkers.C160ToC170OverloadingRules.C164AvoidConversionOperatorsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C80ToC89OtherDefaultOperationRules.C83ValueLikeTypesShouldHaveSwapCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C80ToC89OtherDefaultOperationRules.C84MakeSwapNoExceptCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C80ToC89OtherDefaultOperationRules.C85NamespaceLevelSwapFunctionCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.ES05ToES34DeclarationRules.ES26DontUseVariableForTwoUnrelatedPurposesCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.ES40ToES64ExpressionRules.ES46_01AvoidLossyFloatingPointToIntegerConversionsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.ES40ToES64ExpressionRules.ES46_02AvoidLossyFloatingPointToIntegerFunctionArgumentConversionsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.ES40ToES64ExpressionRules.ES46_03AvoidLossyIntToCharBigConversionsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.ES40ToES64ExpressionRules.ES46_04AvoidLossyIntToCharBigFunctionArgumentConversionsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.ES40ToES64ExpressionRules.ES46_05AvoidLossyIntToCharSmallConversionsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.ES40ToES64ExpressionRules.ES46_06AvoidLossyIntToCharSmallFunctionArgumentConversionsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.ES40ToES64ExpressionRules.ES46_07AvoidLossySignedToUnsignedConversionsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.ES40ToES64ExpressionRules.ES46_08AvoidLossySignedToUnsignedFunctionArgumentConversionsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.ES40ToES64ExpressionRules.ES46_09AvoidLossyIntegerConversionsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.ES40ToES64ExpressionRules.ES46_10AvoidLossyIntegerFunctionArgumentConversionsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.ES40ToES64ExpressionRules.ES46_11AvoidLossyFloatingPointConversionsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.ES40ToES64ExpressionRules.ES46_12AvoidLossyFloatingPointFunctionArgumentConversionsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.ES40ToES64ExpressionRules.ES49_01IfMustUseNamedCastCheckerTraditionalTest;
import com.cevelop.gslator.tests.tests.checkers.ES40ToES64ExpressionRules.ES49_02IfMustUseNamedCastCheckerFunctionalTest;
import com.cevelop.gslator.tests.tests.checkers.ES70ToES86StatementRules.ES74DeclareLoopVariableInTheInitializerCheckerTest;
import com.cevelop.gslator.tests.tests.quickfixes.C160ToC170OverloadingRules.C164AvoidConversionOperatorsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C80ToC89OtherDefaultOperationRules.C83_01ValueLikeTypesShouldHaveSwapQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C80ToC89OtherDefaultOperationRules.C83_02SwapParamIsNotReferenceQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C80ToC89OtherDefaultOperationRules.C84MakeSwapNoExceptQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C80ToC89OtherDefaultOperationRules.C85NamespaceLevelSwapFunctionQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_01_01AvoidLossyFloatingPointToIntegerConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_01_02AvoidLossyFloatingPointToIntegerFunctionArgumentConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_01_03AvoidLossyIntToCharBigConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_01_04AvoidLossyIntToCharBigFunctionArgumentConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_01_05AvoidLossyIntToCharSmallConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_01_06AvoidLossyIntToCharSmallFunctionArgumentConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_01_07AvoidLossySignedToUnsignedConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_01_08AvoidLossySignedToUnsignedFunctionArgumentConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_01_09AvoidLossyIntegerConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_01_10AvoidLossyIntegerFunctionArgumentConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_01_11AvoidLossyFloatingPointConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_01_12AvoidLossyFloatingPointFunctionArgumentConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_02_01AvoidLossyFloatingPointToIntegerConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_02_02AvoidLossyFloatingPointToIntegerFunctionArgumentConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_02_03AvoidLossyIntToCharBigConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_02_04AvoidLossyIntToCharBigFunctionArgumentConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_02_05AvoidLossyIntToCharSmallConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_02_06AvoidLossyIntToCharSmallFunctionArgumentConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_02_07AvoidLossySignedToUnsignedConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_02_08AvoidLossySignedToUnsignedFunctionArgumentConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_02_09AvoidLossyIntegerConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_02_10AvoidLossyIntegerFunctionArgumentConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_02_11AvoidLossyFloatingPointConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES46_02_12AvoidLossyFloatingPointFunctionArgumentConversionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES49_01UseStaticCastQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES49_02_01UseReinterpretCastQuickFixEnabledTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES40ToES64ExpressionRules.ES49_02_02UseReinterpretCastQuickFixDisabledTest;
import com.cevelop.gslator.tests.tests.quickfixes.ES70ToES86StatementRules.ES74DeclareLoopVariableInTheInitializerQuickFixTest;


@RunWith(Suite.class)
@SuiteClasses({
   // @formatter:off
	C83ValueLikeTypesShouldHaveSwapCheckerTest.class,
	C83_01ValueLikeTypesShouldHaveSwapQuickFixTest.class,
	C83_02SwapParamIsNotReferenceQuickFixTest.class,
	C84MakeSwapNoExceptCheckerTest.class,
	C84MakeSwapNoExceptQuickFixTest.class,
	C85NamespaceLevelSwapFunctionCheckerTest.class,
	C85NamespaceLevelSwapFunctionQuickFixTest.class,
	C164AvoidConversionOperatorsCheckerTest.class,
	C164AvoidConversionOperatorsQuickFixTest.class,
	ES26DontUseVariableForTwoUnrelatedPurposesCheckerTest.class,
	ES46_01AvoidLossyFloatingPointToIntegerConversionsCheckerTest.class,
	ES46_02AvoidLossyFloatingPointToIntegerFunctionArgumentConversionsCheckerTest.class,
	ES46_03AvoidLossyIntToCharBigConversionsCheckerTest.class,
	ES46_04AvoidLossyIntToCharBigFunctionArgumentConversionsCheckerTest.class,
	ES46_05AvoidLossyIntToCharSmallConversionsCheckerTest.class,
	ES46_06AvoidLossyIntToCharSmallFunctionArgumentConversionsCheckerTest.class,
	ES46_07AvoidLossySignedToUnsignedConversionsCheckerTest.class,
	ES46_08AvoidLossySignedToUnsignedFunctionArgumentConversionsCheckerTest.class,
	ES46_09AvoidLossyIntegerConversionsCheckerTest.class,
	ES46_10AvoidLossyIntegerFunctionArgumentConversionsCheckerTest.class,
	ES46_11AvoidLossyFloatingPointConversionsCheckerTest.class,
	ES46_12AvoidLossyFloatingPointFunctionArgumentConversionsCheckerTest.class,
	ES46_01_01AvoidLossyFloatingPointToIntegerConversionsQuickFixTest.class,
	ES46_01_02AvoidLossyFloatingPointToIntegerFunctionArgumentConversionsQuickFixTest.class,
	ES46_01_03AvoidLossyIntToCharBigConversionsQuickFixTest.class,
	ES46_01_04AvoidLossyIntToCharBigFunctionArgumentConversionsQuickFixTest.class,
	ES46_01_05AvoidLossyIntToCharSmallConversionsQuickFixTest.class,
	ES46_01_06AvoidLossyIntToCharSmallFunctionArgumentConversionsQuickFixTest.class,
	ES46_01_07AvoidLossySignedToUnsignedConversionsQuickFixTest.class,
	ES46_01_08AvoidLossySignedToUnsignedFunctionArgumentConversionsQuickFixTest.class,
	ES46_01_09AvoidLossyIntegerConversionsQuickFixTest.class,
	ES46_01_10AvoidLossyIntegerFunctionArgumentConversionsQuickFixTest.class,
	ES46_01_11AvoidLossyFloatingPointConversionsQuickFixTest.class,
	ES46_01_12AvoidLossyFloatingPointFunctionArgumentConversionsQuickFixTest.class,
	ES46_02_01AvoidLossyFloatingPointToIntegerConversionsQuickFixTest.class,
	ES46_02_02AvoidLossyFloatingPointToIntegerFunctionArgumentConversionsQuickFixTest.class,
	ES46_02_03AvoidLossyIntToCharBigConversionsQuickFixTest.class,
	ES46_02_04AvoidLossyIntToCharBigFunctionArgumentConversionsQuickFixTest.class,
	ES46_02_05AvoidLossyIntToCharSmallConversionsQuickFixTest.class,
	ES46_02_06AvoidLossyIntToCharSmallFunctionArgumentConversionsQuickFixTest.class,
	ES46_02_07AvoidLossySignedToUnsignedConversionsQuickFixTest.class,
	ES46_02_08AvoidLossySignedToUnsignedFunctionArgumentConversionsQuickFixTest.class,
	ES46_02_09AvoidLossyIntegerConversionsQuickFixTest.class,
	ES46_02_10AvoidLossyIntegerFunctionArgumentConversionsQuickFixTest.class,
	ES46_02_11AvoidLossyFloatingPointConversionsQuickFixTest.class,
	ES46_02_12AvoidLossyFloatingPointFunctionArgumentConversionsQuickFixTest.class,
	ES49_01IfMustUseNamedCastCheckerTraditionalTest.class,
	ES49_02IfMustUseNamedCastCheckerFunctionalTest.class,
	ES49_01UseStaticCastQuickFixTest.class,
	ES49_02_01UseReinterpretCastQuickFixEnabledTest.class,
	ES49_02_02UseReinterpretCastQuickFixDisabledTest.class,
	ES74DeclareLoopVariableInTheInitializerCheckerTest.class,
	ES74DeclareLoopVariableInTheInitializerQuickFixTest.class
	// @formatter:on
})
public class TestSuite_02_SA2016 {}
