package com.cevelop.gslator.tests.suites;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

import com.cevelop.gslator.tests.tests.checkers.C20ToC22DefaultOperationsRules.C20RedundantOperationsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C20ToC22DefaultOperationsRules.C21MissingSpecialMemberFunctionsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C30ToC37DestructorRules.C31_01NoDestructorCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C30ToC37DestructorRules.C31_02DestructorHasNoBodyCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C30ToC37DestructorRules.C31_03DestructorWithMissingDeleteStatementsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C30ToC37DestructorRules.C35BaseClassDestructorCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C30ToC37DestructorRules.C37DestructorShouldBeNoExceptCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C40ToC52ConstructorRules.C44NoexceptDefaultCtorCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C40ToC52ConstructorRules.C45_01DefaultInClassInitializeCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C40ToC52ConstructorRules.C45_02UseInClassInitializerForConstValsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C40ToC52ConstructorRules.C46DeclareSingleCtorExplicitCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C40ToC52ConstructorRules.C47InitializeMemVarsInRightOrderCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C40ToC52ConstructorRules.C48PreferInClassInitializerToCtorsCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C40ToC52ConstructorRules.C49NoAssignmentsInCtorCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C60ToC67CopyMoveRules.C60_01CopyAssignmentNonVirtualCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C60ToC67CopyMoveRules.C60_02CopyAssignmentParameterByConstRefCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C60ToC67CopyMoveRules.C60_03CopyAssignmentReturnByNonConstRefCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C60ToC67CopyMoveRules.C63_01MoveAssignmentNonVirtualCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C60ToC67CopyMoveRules.C63_02MoveAssignmentReturnByNonConstRefCheckerTest;
import com.cevelop.gslator.tests.tests.checkers.C60ToC67CopyMoveRules.C66MoveOperationsShouldBeNoExceptCheckerTest;
import com.cevelop.gslator.tests.tests.quickfixes.C20ToC22DefaultOperationsRules.C20RedundantOperationsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C20ToC22DefaultOperationsRules.C21MissingSpecialMemberFunctionsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C30ToC37DestructorRules.C31_01NoDestructorQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C30ToC37DestructorRules.C31_02DestructorHasNoBodyQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C30ToC37DestructorRules.C31_03DestructorWithMissingDeleteStatementsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C30ToC37DestructorRules.C35BaseClassDestructorQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C30ToC37DestructorRules.C37DestructorShouldBeNoExceptQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C40ToC52ConstructorRules.C44NoexceptDefaultCtorQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C40ToC52ConstructorRules.C45_01DefaultInClassInitializeQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C40ToC52ConstructorRules.C45_02UseInClassInitializerForConstValsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C40ToC52ConstructorRules.C46DeclareSingleCtorExplicitQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C40ToC52ConstructorRules.C47InitializeMemVarsInRightOrderQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C40ToC52ConstructorRules.C48PreferInClassInitializerToCtorsQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C40ToC52ConstructorRules.C49NoAssignmentsInCtorQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C60ToC67CopyMoveRules.C60_01CopyAssignmentNonVirtualQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C60ToC67CopyMoveRules.C60_02CopyAssignmentParameterByConstRefQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C60ToC67CopyMoveRules.C60_03CopyAssignmentReturnByNonConstRefQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C60ToC67CopyMoveRules.C63_01MoveAssignmentNonVirtualQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C60ToC67CopyMoveRules.C63_02MoveAssignmentReturnByNonConstRefQuickFixTest;
import com.cevelop.gslator.tests.tests.quickfixes.C60ToC67CopyMoveRules.C66MoveOperationsShouldBeNoExceptQuickFixTest;


@RunWith(Suite.class)
@SuiteClasses({
   // @formatter:off
	C20RedundantOperationsCheckerTest.class,
	C20RedundantOperationsQuickFixTest.class,
	C21MissingSpecialMemberFunctionsCheckerTest.class,
	C21MissingSpecialMemberFunctionsQuickFixTest.class,
	C31_01NoDestructorCheckerTest.class,
	C31_01NoDestructorQuickFixTest.class,
	C31_02DestructorHasNoBodyCheckerTest.class,
	C31_02DestructorHasNoBodyQuickFixTest.class,
	C31_03DestructorWithMissingDeleteStatementsCheckerTest.class,
	C31_03DestructorWithMissingDeleteStatementsQuickFixTest.class,
	C35BaseClassDestructorCheckerTest.class,
	C35BaseClassDestructorQuickFixTest.class,
	C37DestructorShouldBeNoExceptCheckerTest.class,
	C37DestructorShouldBeNoExceptQuickFixTest.class,
	C44NoexceptDefaultCtorCheckerTest.class,
	C44NoexceptDefaultCtorQuickFixTest.class,
	C45_01DefaultInClassInitializeCheckerTest.class,
	C45_01DefaultInClassInitializeQuickFixTest.class,
	C45_02UseInClassInitializerForConstValsCheckerTest.class,
	C45_02UseInClassInitializerForConstValsQuickFixTest.class,
	C46DeclareSingleCtorExplicitCheckerTest.class,
	C46DeclareSingleCtorExplicitQuickFixTest.class,
	C47InitializeMemVarsInRightOrderCheckerTest.class,
	C47InitializeMemVarsInRightOrderQuickFixTest.class,
	C48PreferInClassInitializerToCtorsCheckerTest.class,
	C48PreferInClassInitializerToCtorsQuickFixTest.class,
	C49NoAssignmentsInCtorCheckerTest.class,
	C49NoAssignmentsInCtorQuickFixTest.class,
	C60_01CopyAssignmentNonVirtualCheckerTest.class,
	C60_01CopyAssignmentNonVirtualQuickFixTest.class,
	C60_02CopyAssignmentParameterByConstRefCheckerTest.class,
	C60_02CopyAssignmentParameterByConstRefQuickFixTest.class,
	C60_03CopyAssignmentReturnByNonConstRefCheckerTest.class,
	C60_03CopyAssignmentReturnByNonConstRefQuickFixTest.class,
	C63_01MoveAssignmentNonVirtualCheckerTest.class,
	C63_01MoveAssignmentNonVirtualQuickFixTest.class,
	C63_02MoveAssignmentReturnByNonConstRefCheckerTest.class,
	C63_02MoveAssignmentReturnByNonConstRefQuickFixTest.class,
	C66MoveOperationsShouldBeNoExceptCheckerTest.class,
	C66MoveOperationsShouldBeNoExceptQuickFixTest.class
	// @formatter:on
})
public class TestSuite_01_BA2016 {}
